#include "Arduino.h"
#include "util.h"

/*
helper function battery_voltage()

LiFePO4 10440 (AAA) 280mAh battery. Used capacity when cycling from 3.25V to 3.00V is about 140mAh.

Recharge battery to 90%: 3.25V
When depleted at 10%: 3.00V
Don't ever let battery go lower than 2.6V
Discharge curve fairly flat from 3.25V to 3.15V
From 3.4V (100% SOC, 300mAh) to 3.25V (90% SOC, 270mAh), convex curve (from 45 degree to flat)
From 3.15V (20% SOC) to 3.0V (10% SOC, 30mAh), concave curve (from flat to 45 degree)
From 3.0V to 2.6V (0% SOC), still concave curve, but rapidly decreasing (from 45 degree to almost 90 degree pointing down)
Add a discharge curve plot on the silkscreen (base plate, along with 'cheat sheet' to use calculator)
Nominal voltage of LiFePO4 battery: 3.2V
MCU voltage range: 1.8V to 5.5V
LCD voltage tolerance range: 3.0V to 3.6V (3.3V ideal): actually shuts down at 2V

store battery ideally at 3.2V (50% of SOC)

Charge battery using CCCV:
first cap current at 56mA to 90mA (0.2C to 0.3C)
then cap charging voltage at 3.5V
Stop charging when battery voltage reaches 3.25V, or when charging current drops to 15mA (0.05C), whichever comes first
should take about 3 to 5 hours to charge battery from 10% SOC to 90% SOC (240mAh).

Typical discharge when on and idle, with backlight off, with battery at 3.2V, is 265uA (mostly from LCD)
0.3mA / 300mAh = 0.001C

Power consumption when on and very active (continually pressing buttons very fast), with backlight off, is 5.7mA.

Power consumption in power down sleep mode is 7.3uA.

Avg current when in active use = 320uA, therefore runtime of about 140mAh / 0.320mA = 428h = 18 days

Avg runtime when in power down sleep mode = 140mAh / 0.0073uA = 19284h = 804 days = 26 months

Voltage measurement code:

Measuring VDD on an AVR128DA28, see http://www.technoblogy.com/show?3K82

The ADC0.MUXPOS register on the AVR128DA28 lets you choose to read a voltage reference option: DACREF0.

DACREF0 is generated by the AC (Analog Comparator) peripheral, as a voltage divider off of the Analog
Comparator's shared voltage reference (VREF.ACREF):
  DACREF0 = AC0.DACREF / 256 * VREF.ACREF

Here, VREF.ACREF is set to VDD (VREF_REFSEL_VDD_gc), and AC0.DACREF is set to 128, so:
  DACREF0 = (128/256) * VDD = VDD / 2

The ADC's own voltage reference (VREF.ADC0REF) is set to 2.048V, and DACREF0 is measured against it:
  ADC0.RES / 4096 * 2.048V = VDD / 2
  VDD = ADC0.RES / 4096 * 4.096V = ADC0.RES / 1000 (in volts)

So the raw 12-bit ADC result IS the battery voltage in millivolts (full scale 4.095V, well above
the 3.0-3.6V LiFePO4 range this calculator runs from). No further scaling arithmetic is needed.

Note DACREF0 ("AC0 DAC Voltage Reference") is a MUXPOS option on the ADC that is independent of
whether AC0's own comparator (AC0.CTRLA.ENABLE) is turned on -- per the datasheet's ADC MUXPOS
selection table (0x49 = DACREF0 = "AC0 DAC Voltage Reference"), so AC0.CTRLA is deliberately left
untouched here.

The ADC is left disabled between readings to save power (this peripheral is only exercised from
the 'config' mode battery-voltage screen, on demand). After enabling it, both the ADC and its
voltage reference need to settle before the first conversion is trustworthy: per the AVR128DA28
datasheet (DS40002183E), Table 37-17 "VREF Specifications" gives tVREF_ST (VREF start-up time)
as typ. 10us when the main clock source is the internal HF oscillator (CLKCTRL.MCLKCTRLA = 0x00,
which is the case here), and Table 37-24 "ADC Conversion Timing Specifications" gives tADC_INIT
(ADC initialization time) as typ. 6us. Neither has a datasheet Max (both are "characterized but
not tested in production"), so a settle delay well above the typicals is used below, plus an
extra conversion is thrown away before the one that's kept, as cheap additional insurance.

*/

// See setupMCU() in main.cpp for the rest of the ADC/AC/VREF peripheral map -- this only
// configures the pieces the battery-voltage reading depends on.
void setupBattVoltMonitor()
{
  VREF.ADC0REF = VREF_REFSEL_2V048_gc;     // Set the ADC's voltage reference to 2.048V.
  VREF.ACREF = VREF_REFSEL_VDD_gc;         // Set the Analog Comparator's shared voltage reference to VDD.
  AC0.DACREF = 128;                        // DACREF0 = (128/256) * VDD = VDD / 2
  ADC0.MUXPOS = ADC_MUXPOS_DACREF0_gc;     // Measure DACREF0
  ADC0.CTRLC = ADC_PRESC_DIV64_gc;         // 375kHz clock (24,000,000 / 64)
  // ADC0.CTRLA (ADC_ENABLE_bm) is deliberately left off here: the ADC is enabled only for the
  // duration of a reading, in read_batt_voltage_mv(), to avoid drawing its idle current
  // continuously.
}

// Reads the battery (VDD) voltage in millivolts. See the comment block above for the derivation:
// with this peripheral configuration, the raw 12-bit ADC result equals VDD in millivolts.
uint16_t read_batt_voltage_mv()
{
  ADC0.CTRLA = ADC_ENABLE_bm;              // Single, 12-bit
  delayMicroseconds(100);                  // let VREF/ADC settle, see comment block above

  // throw away one conversion as extra settling insurance before trusting a result
  ADC0.COMMAND = ADC_STCONV_bm;
  while (ADC0.COMMAND & ADC_STCONV_bm);

  ADC0.COMMAND = ADC_STCONV_bm;            // Start conversion
  while (ADC0.COMMAND & ADC_STCONV_bm);    // Wait for completion
  uint16_t voltage_mv = ADC0.RES;          // ADC conversion result, see comment block above

  ADC0.CTRLA &= ~ADC_ENABLE_bm;            // power down the ADC until next reading

  return voltage_mv;
} // read_batt_voltage_mv()
